// payroll-frontend/src/components/payroll/PayrollProcess.tsx
import React, { useState, useEffect } from 'react';
import { useEmployees } from '../../contexts/EmployeeContext';
import { useCompany } from '../../contexts/CompanyContext';
import { useStatusMessages } from '../../contexts/StatusMessageContext';
import { useAuth } from '../../contexts/AuthContext';
import { payrollService } from '../../services/api';
import { calculateSalary, formatCurrency } from '../../utils/salaryCalculator';
import TopUpModal from '../shared/TopUpModal';
import type { PayrollBatch, TopUpRequest } from '../../types';

// Local payroll item interface for calculations
interface LocalPayrollItem {
  id: string;
  employeeId: string;
  employee: any;
  basic: number;
  hra: number;
  medical: number;
  gross: number;
  status: 'PENDING';
}

const PayrollProcess: React.FC = () => {
  const { employees } = useEmployees();
  const { company, loadCompanyAccount, topUpAccount } = useCompany();
  const { addMessage } = useStatusMessages();
  const { user } = useAuth();
  const [baseSalaryGrade6, setBaseSalaryGrade6] = useState(30000);
  const [payrollBatch, setPayrollBatch] = useState<PayrollBatch | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [showTopUpModal, setShowTopUpModal] = useState(false);
  const [requiredTopUp, setRequiredTopUp] = useState(0);
  const [payrollItems, setPayrollItems] = useState<any[]>([]);
  const [salarySheet, setSalarySheet] = useState<any>(null);

  // Calculate payroll items (local, for summary)
  const _payrollItems: LocalPayrollItem[] = employees.map(employee => {
    const salary = calculateSalary(employee.grade.rank, baseSalaryGrade6);
    return {
      id: `item-${employee.id}`,
      employeeId: employee.id,
      employee,
      basic: salary.basic,
      hra: salary.hra,
      medical: salary.medical,
      gross: salary.gross,
      status: 'PENDING' as const,
    };
  });

  const totalPayroll = _payrollItems.reduce((sum, item) => sum + item.gross, 0);
  const companyBalance = company?.mainAccount?.currentBalance || 0;
  const isInsufficientFunds = companyBalance < totalPayroll;

  // Initial load: Always call pending-batch API when company.id is set
  useEffect(() => {
    if (!company?.id) return;
    async function fetchPendingBatch() {
      try {
        const pendingBatch = await payrollService.getPendingBatch(company.id);
        if (pendingBatch && pendingBatch.id) {
          setPayrollBatch(pendingBatch);
          if (pendingBatch.basicBaseAmount?.amount) {
            setBaseSalaryGrade6(pendingBatch.basicBaseAmount.amount);
          }
        } else {
          setPayrollBatch(null);
          setPayrollItems([]);
        }
      } catch {
        setPayrollBatch(null);
        setPayrollItems([]);
      }
    }
    fetchPendingBatch();
  }, [company?.id]);

  // Fetch payroll batch items from backend when batch changes
  useEffect(() => {
    if (payrollBatch && payrollBatch.id) {
      payrollService.getPayrollBatchItems(payrollBatch.id, 0, 10, 'amount')
        .then((data) => {
          setPayrollItems(data.content || []);
        })
        .catch(() => setPayrollItems([]));
    } else {
      setPayrollItems([]);
    }
  }, [payrollBatch]);

  // Utility: Refresh batch status from backend
  const refreshBatchStatus = async () => {
    const batchId = localStorage.getItem('payrollBatchId');
    if (batchId) {
      try {
        const batch = await payrollService.getPayrollBatchById(batchId);
        setPayrollBatch(batch);
        localStorage.setItem('payrollBatchInfo', JSON.stringify(batch));
        localStorage.setItem('payrollBatchStatus', batch.payrollStatus || batch.status);
      } catch {
        setPayrollBatch(null);
        localStorage.removeItem('payrollBatchInfo');
        localStorage.removeItem('payrollBatchId');
        localStorage.removeItem('payrollBatchStatus');
      }
    }
  };

  // After transfer, batch creation, or reload, always refresh batch status
  useEffect(() => {
    refreshBatchStatus();
  }, []);

  // Payroll batch creation (real backend)
  const handleCreateBatch = async () => {
    if (employees.length !== 10) {
      addMessage('error', 'Cannot process payroll: Must have exactly 10 employees');
      return;
    }
    if (!company?.id || !company?.mainAccount?.id) {
      addMessage('error', 'Company or main account information missing.');
      return;
    }

    // Prevent duplicate batch creation
    const batchStatus = payrollBatch ? (payrollBatch.payrollStatus || payrollBatch.status || '') : '';
    if (batchStatus === 'PENDING' || batchStatus === 'PARTIALLY_COMPLETED') {
      addMessage('error', 'A payroll batch is already in progress. Please complete or fail the current batch before creating a new one.');
      return;
    }

    // Check if sufficient funds
    if (isInsufficientFunds) {
      addMessage('error', `Insufficient funds! Need ${formatCurrency(totalPayroll - companyBalance)} more.`);
      setRequiredTopUp(totalPayroll - companyBalance);
      setShowTopUpModal(true);
      return;
    }

    setIsProcessing(true);
    try {
      const payload = {
        name: `${new Date().toLocaleString('default', { month: 'long', year: 'numeric' })} Payroll`,
        payrollMonth: new Date().toISOString().slice(0, 10),
        companyId: company.id,
        fundingAccountId: company.mainAccount.id,
        description: `${new Date().toLocaleString('default', { month: 'long', year: 'numeric' })} Payroll Distribution`,
        baseSalary: baseSalaryGrade6
      };
      const batch = await payrollService.createPayrollBatch(payload);
      setPayrollBatch(batch);
      localStorage.setItem('payrollBatchId', batch.id);
      localStorage.setItem('payrollBatchStatus', batch.payrollStatus || batch.status);
      localStorage.setItem('payrollBatchInfo', JSON.stringify(batch));
      addMessage('success', 'Payroll batch created. Ready for transfer.', `Batch ID: ${batch.id}`);
      await loadCompanyAccount();
    } catch (error: any) {
      addMessage('error', 'Failed to create payroll batch', error.response?.data?.message || error.message);
    } finally {
      setIsProcessing(false);
    }
  };

  // Transfer salaries for batch
  const handleTransferSalaries = async () => {
    if (!payrollBatch) return;
    
    // Get employee IDs from payroll items
    const employeeIds = payrollItems.length > 0 
      ? payrollItems.map(item => item.employeeId || item.id)
      : employees.map(emp => emp.id);
    
    setIsProcessing(true);
    try {
      const request = {
        employeeIds,
        grade6Basic: baseSalaryGrade6
      };
      const transferResult = await payrollService.processSalaryTransfer(request);
      const successCount = transferResult.transferResults.filter(r => r.status === 'SUCCESS').length;
      addMessage('success', 'Salary transfer processed.', `${successCount} of ${transferResult.transferResults.length} transfers successful`);
      
      // Refresh batch info and company balance
      const updatedBatch = await payrollService.getPayrollBatchById(payrollBatch.id);
      setPayrollBatch(updatedBatch);
      localStorage.setItem('payrollBatchInfo', JSON.stringify(updatedBatch));
      localStorage.setItem('payrollBatchStatus', updatedBatch.payrollStatus || updatedBatch.status);
      await loadCompanyAccount();
      
      // If batch is complete or failed, clear batch info
      const finalStatus = updatedBatch.payrollStatus || updatedBatch.status;
      if (finalStatus === 'COMPLETED' || finalStatus === 'FAILED') {
        localStorage.removeItem('payrollBatchInfo');
        localStorage.removeItem('payrollBatchId');
        localStorage.removeItem('payrollBatchStatus');
        setPayrollBatch(null);
      }
    } catch (error: any) {
      addMessage('error', 'Failed to transfer salaries', error.response?.data?.message || error.message);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleTopUpComplete = async (request: TopUpRequest) => {
    try {
      await topUpAccount(request);
      await loadCompanyAccount();
      addMessage('success', `Account topped up with ${formatCurrency(request.amount)}`, 'You can now process payroll.');
      setShowTopUpModal(false);
    } catch (error: any) {
      addMessage('error', 'Failed to top up account', error.response?.data?.message || error.message);
      throw error;
    }
  };

  // Button logic strictly from batch status
  const batchStatus = payrollBatch ? ((payrollBatch as any).payrollStatus || payrollBatch.status || '') : '';
  const isBatchComplete = batchStatus === 'COMPLETED' || batchStatus === 'FAILED';
  const isBatchActive = batchStatus === 'PENDING' || batchStatus === 'PARTIALLY_COMPLETED';
  const canManagePayroll = user?.role === 'ADMIN' || user?.role === 'EMPLOYER';

  let calculateButtonDisabled = true;
  let transferButtonDisabled = true;
  if (canManagePayroll) {
    if (isBatchActive) {
      calculateButtonDisabled = true;
      transferButtonDisabled = false;
    } else {
      calculateButtonDisabled = isProcessing || employees.length !== 10;
      transferButtonDisabled = true;
    }
  } else {
    calculateButtonDisabled = true;
    transferButtonDisabled = true;
  }

  // Debug logging
  console.log('🔍 PayrollProcess State:', {
    payrollBatch: payrollBatch ? { id: payrollBatch.id, status: batchStatus } : null,
    batchStatus,
    isBatchActive,
    isBatchComplete,
    canManagePayroll,
    userRole: user?.role
  });

  // Salary sheet and transfer should use batchId from pending batch or transfer response
  const salarySheetBatchId = payrollBatch?.id || localStorage.getItem('payrollBatchId');

  // Fetch salary sheet using batchId
  useEffect(() => {
    async function fetchSalarySheet() {
      if (salarySheetBatchId) {
        try {
          const sheet = await payrollService.getPayrollBatchById(salarySheetBatchId);
          setSalarySheet(sheet);
        } catch {
          setSalarySheet(null);
        }
      } else {
        setSalarySheet(null);
      }
    }
    fetchSalarySheet();
  }, [salarySheetBatchId]);

  return (
    <div className="payroll-process">
      <div className="page-header">
        <h2>Payroll Processing</h2>
        <div className="salary-config">
          <label>Base Salary (Grade 6):</label>
          <input
            type="number"
            value={baseSalaryGrade6}
            onChange={(e) => setBaseSalaryGrade6(Number(e.target.value))}
            min="10000"
            step="1000"
            disabled={calculateButtonDisabled}
          />
        </div>
      </div>

      {/* Payroll Summary */}
      <div className="payroll-summary">
        <div className="summary-card">
          <h3>Payroll Summary</h3>
          <div className="summary-stats">
            <div className="stat">
              <label>Total Employees:</label>
              <span>{employees.length} / 10</span>
            </div>
            <div className="stat">
              <label>Total Payroll:</label>
              <span className="amount">{formatCurrency(totalPayroll)}</span>
            </div>
            <div className="stat">
              <label>Company Balance:</label>
              <span className={`amount ${isInsufficientFunds ? 'insufficient' : 'sufficient'}`}>
                {formatCurrency(companyBalance)}
              </span>
            </div>
            <div className="stat">
              <label>After Payroll:</label>
              <span className={`amount ${companyBalance - totalPayroll < 0 ? 'negative' : 'positive'}`}>
                {formatCurrency(companyBalance - totalPayroll)}
              </span>
            </div>
          </div>
        </div>

        {/* Process/Transfer Buttons */}
        <div className="process-actions">
          {isInsufficientFunds && !isBatchActive && (
            <div className="insufficient-funds-warning">
              <p>⚠️ Insufficient funds! Need {formatCurrency(totalPayroll - companyBalance)} more.</p>
            </div>
          )}

          {/* Only admin/employer can use buttons */}
          {canManagePayroll ? (
            <>
              <button
                onClick={handleCreateBatch}
                disabled={calculateButtonDisabled}
                className={`process-btn ${isInsufficientFunds && !isBatchActive ? 'top-up' : 'process'}`}
              >
                {isProcessing ? '⏳ Creating Batch...' : '✅ Calculate All Salaries'}
              </button>
              <button
                onClick={handleTransferSalaries}
                disabled={transferButtonDisabled}
                className="process-btn transfer-btn"
              >
                {isProcessing ? '⏳ Transferring...' : '💸 Transfer Salaries'}
              </button>
              {/* Status messages */}
              {isBatchActive && (
                <div className="batch-status-info">
                  <p>✅ Batch ready for transfer (Status: {batchStatus})</p>
                </div>
              )}
              {isBatchComplete && (
                <div className="batch-status-info">
                  <p>Batch {batchStatus}. You can calculate new payroll.</p>
                </div>
              )}
            </>
          ) : (
            <div className="access-denied">
              <p>⚠️ Only ADMIN or EMPLOYER can process payroll</p>
            </div>
          )}
          {employees.length !== 10 && (
            <div className="employee-warning">
              <p>⚠️ Must have exactly 10 employees to process payroll</p>
            </div>
          )}
        </div>
      </div>

      {/* Salary Breakdown Table */}
      <div className="salary-breakdown">
        <h3>Salary Breakdown</h3>
        <div className="table-container">
          {/* Debug output for troubleshooting */}
          <pre style={{ display: 'none' }}>{JSON.stringify({payrollBatch, payrollItems, localPayrollItems: payrollItems}, null, 2)}</pre>
          <table className="salary-table">
            <thead>
              <tr>
                <th>Employee ID</th>
                <th>Name</th>
                <th>Grade</th>
                <th>Basic</th>
                <th>HRA (20%)</th>
                <th>Medical (15%)</th>
                <th>Gross Salary</th>
                <th>Net Amount</th>
                <th>Status</th>
                <th>Failure Reason</th>
                <th>Account Number</th>
              </tr>
            </thead>
            <tbody>
              {(payrollBatch && payrollItems.length > 0 ? payrollItems : payrollItems).map(item => (
                <tr key={item.id || item.employeeId} className={item.status?.toLowerCase() || ''}>
                  <td>{item.employeeBizId || item.employee?.code}</td>
                  <td>{item.employeeName || item.employee?.name}</td>
                  <td>{item.grade || (item.employee?.grade ? `Grade ${item.employee.grade.rank}` : '')}</td>
                  <td>{formatCurrency(item.basicSalary?.amount ?? item.basic ?? 0)}</td>
                  <td>{formatCurrency(item.hra?.amount ?? item.hra ?? 0)}</td>
                  <td>{formatCurrency(item.medicalAllowance?.amount ?? item.medical ?? 0)}</td>
                  <td>{formatCurrency(item.grossSalary?.amount ?? item.gross ?? 0)}</td>
                  <td>{formatCurrency(item.netAmount?.amount ?? item.gross ?? 0)}</td>
                  <td><span className={`status-badge ${item.status?.toLowerCase()}`}>{item.status}</span></td>
                  <td>{item.failureReason || ''}</td>
                  <td>{item.accountNumber || (item.employee?.account?.accountNumber || '')}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="total-row">
                <td colSpan={6}><strong>Total Payroll</strong></td>
                <td><strong>{formatCurrency(totalPayroll)}</strong></td>
                <td></td>
              </tr>
            </tfoot>
          </table>
          {/* If no data, show a message */}
          {((payrollBatch && payrollItems.length === 0) || (!payrollBatch && payrollItems.length === 0)) && (
            <div className="no-data">No payroll items to display.</div>
          )}
        </div>
      </div>

      {/* Salary Sheet Overview */}
      {salarySheet && (
        <div className="salary-sheet-overview">
          <h3>Salary Sheet Overview</h3>
          <div className="sheet-summary">
            <div><strong>PAY TO BE AMOUNT</strong><br />BDT {salarySheet.totalAmount?.amount?.toLocaleString() || 0}</div>
            <div><strong>TOTAL PAID AMOUNT</strong><br />BDT {salarySheet.executedAmount?.amount?.toLocaleString() || 0}</div>
            <div><strong>COMPANY ACCOUNT BALANCE</strong><br />BDT {company?.mainAccount?.currentBalance?.toLocaleString() || 0}</div>
          </div>
          <table className="salary-table">
            <thead>
              <tr>
                <th>Name (ID)</th>
                <th>Grade</th>
                <th>Basic</th>
                <th>HRA</th>
                <th>Medical</th>
                <th>Gross Salary</th>
              </tr>
            </thead>
            <tbody>
              {(salarySheet.items || []).map((item: any) => (
                <tr key={item.employeeId}>
                  <td>{item.employeeName} <br />ID: {item.employeeBizId}</td>
                  <td>{item.grade}</td>
                  <td>BDT {item.basicSalary?.amount?.toLocaleString() || 0}</td>
                  <td>BDT {item.hra?.amount?.toLocaleString() || 0}</td>
                  <td>BDT {item.medicalAllowance?.amount?.toLocaleString() || 0}</td>
                  <td>BDT {item.grossSalary?.amount?.toLocaleString() || 0}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Processed Batch Results */}
      {payrollBatch && (
        <div className="batch-results">
          <h3>Payroll Batch Results</h3>
          <div className="batch-info">
            <p><strong>Batch ID:</strong> {payrollBatch.id}</p>
            <p><strong>Status:</strong> <span className={`status-badge ${payrollBatch.status.toLowerCase()}`}>{payrollBatch.status}</span></p>
            <p><strong>Total Amount:</strong> {formatCurrency(payrollBatch.totalAmount?.amount ?? 0)}</p>
            <p><strong>Processed At:</strong> {payrollBatch.executedAt ? new Date(payrollBatch.executedAt).toLocaleString() : 'N/A'}</p>
          </div>
        </div>
      )}

      {/* Top-up Modal */}
      <TopUpModal
        isOpen={showTopUpModal}
        onClose={() => setShowTopUpModal(false)}
        onTopUp={handleTopUpComplete}
        requiredAmount={requiredTopUp}
        currentBalance={company?.mainAccount?.currentBalance || 0}
      />
    </div>
  );
};

export default PayrollProcess;

// payroll-angular/src/app/components/payroll/payroll-process.component.ts
import { Component, signal, computed, inject, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { PayrollService } from '../../services/payroll.service';
import { CompanyService } from '../../services/company.service';
import { EmployeeService } from '../../services/employee.service';
import { formatCurrency, calculateBasicSalary } from '../../simulator/salary-calculator';
import { ToastMessageComponent } from '../shared/toast-message.component';
import { LoadingSpinnerComponent } from '../shared/loading-spinner.component';
import type { Employee } from '../../models/api.types';

@Component({
  selector: 'app-payroll-process',
  standalone: true,
  imports: [CommonModule, FormsModule, ToastMessageComponent, LoadingSpinnerComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './payroll-process.component.html',
  styleUrls: ['./payroll-process.component.css']
})
export class PayrollProcessComponent implements OnInit {
  private payrollService = inject(PayrollService);
  private companyService = inject(CompanyService);
  private employeeService = inject(EmployeeService);

  employees = signal<Employee[]>([]);
  companyId = signal('');
  companyBalance = signal(0);

  ngOnInit() {
    this.loadData();
  }

  loadData() {
    this.loading.set(true);
    this.employeeService.getAll().subscribe({
      next: (data) => {
        this.employees.set(data);
        if (data.length > 0 && data[0].company) {
          this.companyId.set(data[0].company.id);
          this.loadCompany(data[0].company.id);
          // Get logged-in user info
          let employeeId: string | undefined = undefined;
          const userStr = typeof window !== 'undefined' && window.localStorage ? window.localStorage.getItem('userProfile') : null;
          if (userStr) {
            try {
              const user = JSON.parse(userStr);
              if (user && user.user && user.user.role === 'EMPLOYEE') {
                employeeId = user.user.id;
              }
            } catch {}
          }
          this.loadLastBatch(data[0].company.id, employeeId);
        }
        this.loading.set(false);
      },
      error: (error) => {
        console.error('Failed to load:', error);
        this.message.set('❌ Failed to load data');
        this.loading.set(false);
      }
    });
  }

  loadLastBatch(companyId: string, employeeId?: string) {
    this.payrollService.getLastBatch(companyId).subscribe({
      next: (batch: any) => {
        if (batch && batch.id) {
          this.batchData.set(batch);
          this.batchId.set(batch.id);
          this.batchName.set(batch.name || 'N/A');
          this.batchStatus.set(batch.payrollStatus || 'PENDING');
          this.payrollMonth.set(batch.payrollMonth || 'N/A');
          this.paymentStatus.set({ totalPaid: batch.executedAmount?.amount || 0, requiredTopUp: 0 });
          // Load payroll items for batch
          this.payrollService.getPayrollItems(batch.id, employeeId).subscribe({
            next: (items: any[]) => {
              this.batchItems.set(items || []);
            },
            error: (err: any) => {
              this.batchItems.set([]);
              console.error('Failed to load payroll items:', err);
            }
          });
        } else {
          this.resetBatchInfo();
        }
      },
      error: (error: any) => {
        console.log('ℹ️ No last batch found:', error);
        this.resetBatchInfo();
      }
    });
  }

  resetBatchInfo() {
    this.batchData.set(null);
    this.batchId.set('');
    this.batchName.set('');
    this.batchStatus.set('');
    this.payrollMonth.set('');
    this.paymentStatus.set({ totalPaid: 0, requiredTopUp: 0 });
    this.batchItems.set([]);
  }

  loadCompany(id: string) {
    this.companyService.getCompany(id).subscribe({
      next: (company) => {
        this.companyBalance.set(company.mainAccount.currentBalance);
      },
      error: (error) => console.error('Failed to load company:', error)
    });
  }

  grade6Basic = signal(25000);
  loading = signal(false);
  message = signal('');
  isTopUpModalOpen = signal(false);
  topUpAmount = signal(0);
  paymentStatus = signal({ totalPaid: 0, requiredTopUp: 0 });
  
  // Pagination
  currentPage = signal(0);
  pageSize = signal(5);
  
  // Batch Information
  batchId = signal('');
  batchName = signal('');
  batchStatus = signal('');
  payrollMonth = signal('');
  batchMonth = signal('');

  GRADE_LEVELS = [6, 5, 4, 3, 2, 1];


  // Salary summary and items are based on last payroll batch, not live input
  // All payroll info comes from backend batch APIs only
  batchData = signal<any>(null);
  batchItems = signal<any[]>([]);

  employeesWithSalaries = computed(() => {
    // Map backend batch items to UI-friendly structure expected by the table
    const items = this.batchItems();
    return (items || []).map((it: any) => {
      const basic = Math.round(it.basicSalary?.amount ?? 0);
      const hra = Math.round(it.hra?.amount ?? it.houseRentAllowance?.amount ?? Math.round(basic * 0.20));
      const medical = Math.round(it.medicalAllowance?.amount ?? Math.round(basic * 0.15));
      const gross = Math.round(it.grossSalary?.amount ?? (basic + hra + medical));
      return {
        id: it.employeeId || it.id,
        code: it.employeeBizId || it.employeeCode || '',
        name: it.employeeName || '',
        grade: { rank: it.grade || it.gradeRank || 0 },
        account: { accountNumber: it.accountNumber || it.employeeAccountNumber || 'N/A' },
        salary: {
          basic,
          houseRent: hra,
          medicalAllowance: medical,
          gross,
          isPaid: it.status ? (it.status === 'PAID') : false
        }
      } as any;
    });
  });

  paginatedEmployees = computed(() => {
    const sorted = this.employeesWithSalaries();
    const page = this.currentPage();
    const size = this.pageSize();
    const startIndex = page * size;
    return sorted.slice(startIndex, startIndex + size);
  });

  totalPages = computed(() => {
    const len = this.employeesWithSalaries().length;
    const size = this.pageSize();
    return len === 0 ? 1 : Math.ceil(len / size);
  });

  calculateSalaries() {
    // Validate employees exist
    if (this.employees().length === 0) {
      this.message.set('⚠️ Cannot create payroll: No employees available');
      return;
    }

    // Check if company exists
    if (!this.companyId()) {
      this.message.set('⚠️ Company information missing');
      return;
    }

    // Check for existing pending batch
    const currentStatus = this.batchStatus();
    if (currentStatus === 'PENDING' || currentStatus === 'PROCESSING' || currentStatus === 'PARTIALLY_COMPLETED') {
      this.message.set('⚠️ A payroll batch is already in progress. Please complete or cancel the current batch.');
      return;
    }

    // Get funding account from company service (not from employee data)
    // We need to fetch full company details to get mainAccount.id
    this.loading.set(true);
    
    this.companyService.getCompany(this.companyId()).subscribe({
      next: (company: any) => {
        const fundingAccountId = company.mainAccount?.id;
        
        console.log('🏦 Company data:', {
          companyId: company.id,
          mainAccount: company.mainAccount,
          fundingAccountId
        });

        if (!fundingAccountId) {
          this.loading.set(false);
          this.message.set('⚠️ Company funding account not found');
          return;
        }

        console.log('🚀 Creating payroll batch with:', {
          companyId: this.companyId(),
          fundingAccountId,
          baseSalary: this.grade6Basic()
        });

        // Create payroll batch payload matching backend API
        const now = new Date();
        const monthName = now.toLocaleString('default', { month: 'long', year: 'numeric' });
        const payload = {
          name: `${monthName} Payroll`,
          payrollMonth: now.toISOString().slice(0, 10), // YYYY-MM-DD format
          companyId: this.companyId(),
          fundingAccountId: fundingAccountId,
          description: `${monthName} Payroll Distribution`,
          baseSalary: this.grade6Basic()
        };

        console.log('📤 Sending create batch request:', payload);

        this.payrollService.createPayrollBatch(payload).subscribe({
          next: (batch: any) => {
            console.log('✅ Batch created successfully:', batch);
            this.loading.set(false);
            this.message.set(`✅ Payroll batch created. Batch ID: ${batch.id}`);
            
            // Update local state with new batch
            this.batchData.set(batch);
            this.batchId.set(batch.id);
            this.batchName.set(batch.name || 'N/A');
            this.batchStatus.set(batch.payrollStatus || batch.status || 'PENDING');
            this.payrollMonth.set(batch.payrollMonth || 'N/A');
            this.paymentStatus.set({ totalPaid: batch.executedAmount?.amount || 0, requiredTopUp: 0 });

            // Reload company balance
            this.loadCompany(this.companyId());

            // Load batch items
            let employeeId: string | undefined = undefined;
            const userStr = typeof window !== 'undefined' && window.localStorage ? window.localStorage.getItem('userProfile') : null;
            if (userStr) {
              try {
                const user = JSON.parse(userStr);
                if (user && user.user && user.user.role === 'EMPLOYEE') {
                  employeeId = user.user.id;
                }
              } catch {}
            }
            this.payrollService.getPayrollItems(batch.id, employeeId).subscribe({
              next: (items: any[]) => {
                this.batchItems.set(items || []);
              },
              error: (err: any) => {
                console.error('Failed to load batch items:', err);
                this.batchItems.set([]);
              }
            });
          },
          error: (error: any) => {
            console.error('❌ Failed to create payroll batch:', error);
            const errorMsg = error.error?.message || error.message || 'Failed to create payroll';
            this.message.set(`❌ ${errorMsg}`);
            this.loading.set(false);
          }
        });
      },
      error: (error: any) => {
        console.error('❌ Failed to load company:', error);
        this.loading.set(false);
        this.message.set('⚠️ Failed to load company information');
      }
    });
  }

  processPayroll() {
    if (!this.batchId()) {
      this.message.set('⚠️ No payroll batch to process');
      return;
    }

    // Compute shortfall: total to be paid minus already executed amount
    const totalToPay = this.batchData()?.totalAmount?.amount || 0;
    const alreadyPaid = this.batchData()?.executedAmount?.amount || 0;
    const remainingToPay = Math.max(0, totalToPay - alreadyPaid);
    const balance = this.companyBalance();

    console.log('💰 Payroll Processing Check:', {
      totalToPay,
      alreadyPaid,
      remainingToPay,
      balance,
      sufficient: remainingToPay <= balance
    });

    // FIXED: Immediately process if funds are sufficient (matching React pattern)
    if (remainingToPay <= balance) {
      console.log('✅ Sufficient funds, processing payroll immediately...');
      this.loading.set(true);
      this.payrollService.processPayrollBatch(this.batchId()).subscribe({
        next: (response: any) => {
          this.loading.set(false);
          this.message.set(`✅ Payroll processed successfully!`);
          console.log('✅ Payroll batch processed:', response);
          // Reload data
          this.loadCompany(this.companyId());
          let employeeId: string | undefined = undefined;
          const userStr = typeof window !== 'undefined' && window.localStorage ? window.localStorage.getItem('userProfile') : null;
          if (userStr) {
            try {
              const user = JSON.parse(userStr);
              if (user && user.user && user.user.role === 'EMPLOYEE') {
                employeeId = user.user.id;
              }
            } catch {}
          }
          this.loadLastBatch(this.companyId(), employeeId);
        },
        error: (error: any) => {
          console.error('❌ Failed to process payroll:', error);
          const errorMsg = error.error?.message || 'Payroll process failed';
          this.message.set(`❌ ${errorMsg}`);
          this.loading.set(false);
        }
      });
    } else {
      // FIXED: Insufficient funds - open modal with required minimum (matching React pattern)
      const shortfall = remainingToPay - balance;
      console.log('⚠️ Insufficient funds, need to top up:', formatCurrency(shortfall));
      this.topUpAmount.set(Math.ceil(shortfall / 1000) * 1000); // Round up to nearest 1000
      // Store min/max constraints via signals (reusing modal UI)
      (this as any).topUpMin = shortfall; // for UI hint
      (this as any).topUpMax = Math.max(shortfall, 1000000); // simple max cap; can be refined
      this.paymentStatus.set({ totalPaid: alreadyPaid, requiredTopUp: shortfall });
      this.isTopUpModalOpen.set(true);
      this.message.set(`⚠️ Insufficient funds! Need ${formatCurrency(shortfall)} more to process payroll`);
    }
  }

  setPage(page: number) {
    const maxPage = this.totalPages() - 1;
    if (page >= 0 && page <= maxPage) {
      this.currentPage.set(page);
    }
  }

  setPageSize(size: number | string) {
    const n = typeof size === 'string' ? parseInt(size, 10) : size;
    this.pageSize.set(isNaN(n as number) ? 5 : (n as number));
    this.currentPage.set(0);
  }

  handleTopUp() {
    const amount = this.topUpAmount();
    const requiredMin = this.paymentStatus().requiredTopUp || 1000;
    const maxCap = 10000000; // 10 million max

    // Validate amount
    if (amount <= 0) {
      this.message.set('⚠️ Please enter a valid amount');
      return;
    }

    if (amount < requiredMin) {
      this.message.set(`⚠️ Minimum top-up amount is ${formatCurrency(requiredMin)}`);
      return;
    }
    
    if (amount > maxCap) {
      this.message.set(`⚠️ Maximum top-up amount is ${formatCurrency(maxCap)}`);
      return;
    }
    
    console.log('💰 Processing top-up:', formatCurrency(amount));
    this.loading.set(true);
    
    this.companyService.topUp(this.companyId(), {
      amount: amount,
      description: 'Emergency top-up for payroll processing'
    }).subscribe({
      next: (response: any) => {
        console.log('✅ Top-up successful:', response);
        
        // Update balance from response or reload
        if (response && 'newBalance' in response) {
          this.companyBalance.set(response.newBalance);
        } else {
          // Reload company data to get updated balance
          this.companyService.getCompany(this.companyId()).subscribe({
            next: (company: any) => {
              this.companyBalance.set(company.mainAccount.currentBalance);
              console.log('✅ Balance reloaded:', formatCurrency(company.mainAccount.currentBalance));
            },
            error: (err: any) => console.error('Failed to reload balance:', err)
          });
        }
        
        this.message.set(`✅ Added ${formatCurrency(amount)}. Processing payroll...`);
        this.topUpAmount.set(0);
        this.isTopUpModalOpen.set(false);
        this.paymentStatus.set({ totalPaid: this.batchData()?.executedAmount?.amount || 0, requiredTopUp: 0 });
        this.loading.set(false);
        
        // CRITICAL: Auto-retry payroll processing after successful topup (matching React pattern)
        if (this.batchId()) {
          console.log('🔄 Auto-retrying payroll processing after top-up...');
          // Small delay to ensure balance is updated
          setTimeout(() => {
            this.processPayroll();
          }, 500);
        }
      },
      error: (error: any) => {
        console.error('❌ Top-up failed:', error);
        const errorMsg = error.error?.message || 'Top-up failed';
        this.message.set(`❌ ${errorMsg}`);
        this.loading.set(false);
      }
    });
  }

  openTopUpModal() {
    this.isTopUpModalOpen.set(true);
  }

  closeTopUpModal() {
    this.isTopUpModalOpen.set(false);
  }

  clearMessage() {
    this.message.set('');
  }

  formatCurrency(amount: number): string {
    return formatCurrency(amount);
  }
}

<div class="payroll-container">
  <h2 class="section-title">💰 Payroll Processing</h2>

  <!-- Payroll Processing Card (added) -->
  <div class="payroll-card">
    <div class="payroll-card-header">⚙️ Payroll Processing</div>
    <div class="payroll-card-body">
      <div class="payroll-input-group">
        <label for="basicSalary" class="payroll-label">Grade 6 Basic Salary (BDT)</label>
        <input
          id="basicSalary"
          type="number"
          class="payroll-input"
          [ngModel]="grade6Basic()"
          (ngModelChange)="grade6Basic.set(+$event)"
          min="10000"
        />
      </div>
      <div class="payroll-actions">
        <button (click)="calculateSalaries()" class="pay-btn primary" [disabled]="loading() || employees().length === 0 || (batchStatus() === 'PENDING' || batchStatus() === 'PROCESSING' || batchStatus() === 'PARTIALLY_COMPLETED')" [title]="employees().length === 0 ? 'No employees available' : (batchStatus() === 'PENDING' || batchStatus() === 'PROCESSING') ? 'Complete or cancel current batch first' : 'Create new payroll batch'">📝 Create Payroll</button>
        <button (click)="processPayroll()" class="pay-btn success" [disabled]="loading() || (batchStatus() !== 'PENDING' && batchStatus() !== 'PROCESSING')">💸 Process Payroll</button>
        @if (paymentStatus().requiredTopUp > 0) {
          <button (click)="openTopUpModal()" class="pay-btn warning">⚠️ Top Up Required</button>
        }
      </div>
    </div>
  </div>

  <!-- Salary Sheet Overview Header -->
  <div class="salary-sheet-header">
    <h3 class="sheet-title">💰 Salary Sheet Overview</h3>
  </div>

  <!-- Salary Overview Cards -->
  <div class="salary-overview">
        <div class="overview-card pay-amount">
          <div class="card-label">PAY TO BE AMOUNT</div>
          <div class="card-value green">{{ formatCurrency(batchData()?.totalAmount?.amount || 0) }}</div>
        </div>
        <div class="overview-card paid-amount">
          <div class="card-label">TOTAL PAID AMOUNT</div>
          <div class="card-value green">{{ formatCurrency(batchData()?.executedAmount?.amount || 0) }}</div>
        </div>
        <div class="overview-card company-balance">
          <div class="card-label">COMPANY ACCOUNT BALANCE</div>
          <div class="card-value" [class.danger]="companyBalance() < (batchData()?.totalAmount?.amount || 0)">
            {{ formatCurrency(companyBalance()) }}
          </div>
        </div>
  </div>

  <!-- Batch Information -->
  <div class="batch-info-card-modern">
    <div class="batch-info-grid">
      <div class="batch-info-item">
        <div class="batch-info-label">
          <span class="batch-icon">🆔</span>
          Batch ID
        </div>
        <div class="batch-info-value">{{ batchId() || 'N/A' }}</div>
      </div>
      <div class="batch-info-item">
        <div class="batch-info-label">
          <span class="batch-icon">📋</span>
          Batch Name
        </div>
        <div class="batch-info-value">{{ batchName() || 'N/A' }}</div>
      </div>
      <div class="batch-info-item">
        <div class="batch-info-label">
          <span class="batch-icon">📊</span>
          Status
        </div>
        <div class="batch-info-value">
          @if (batchStatus()) {
            <span class="batch-status-pill" 
                  [class.completed]="batchStatus() === 'COMPLETED' || batchStatus() === 'PARTIALLY_COMPLETED'" 
                  [class.pending]="batchStatus() === 'PENDING' || batchStatus() === 'PROCESSING'">
              {{ batchStatus() }}
            </span>
          } @else {
            <span class="batch-info-na">N/A</span>
          }
        </div>
      </div>
      <div class="batch-info-item">
        <div class="batch-info-label">
          <span class="batch-icon">📅</span>
          Payroll Month
        </div>
        <div class="batch-info-value">{{ payrollMonth() || 'N/A' }}</div>
      </div>
    </div>
  </div>

  <!-- Salary Sheet -->
  <div class="table-wrapper">
    <div class="table-container">
      <table class="salary-table">
      <thead class="table-header">
        <tr>
          <th class="table-cell">Name (ID)</th>
          <th class="table-cell text-center">Account Number</th>
          <th class="table-cell text-center">Grade</th>
          <th class="table-cell text-right">Basic</th>
          <th class="table-cell text-right">HRA (20%)</th>
          <th class="table-cell text-right">Medical (15%)</th>
          <th class="table-cell text-right">Gross Salary</th>
          <th class="table-cell text-center">Net Amount</th>
          <th class="table-cell text-center">Status</th>
        </tr>
      </thead>
      <tbody class="table-body">
        @for (emp of paginatedEmployees(); track emp.id) {
          <tr [class.paid-row]="emp.salary?.isPaid">
            <td class="table-cell">
              <div class="employee-info">
                <div class="employee-name">{{ emp.name }}</div>
                <div class="employee-id">ID: {{ emp.code }}</div>
              </div>
            </td>
            <td class="table-cell text-center">
              <span class="account-number">{{ emp.account.accountNumber || 'N/A' }}</span>
            </td>
            <td class="table-cell text-center">
              <span class="grade-badge">G{{ emp.grade.rank }}</span>
            </td>
            <td class="table-cell text-right">{{ formatCurrency(emp.salary?.basic || 0) }}</td>
            <td class="table-cell text-right">{{ formatCurrency(emp.salary?.houseRent || 0) }}</td>
            <td class="table-cell text-right">{{ formatCurrency(emp.salary?.medicalAllowance || 0) }}</td>
            <td class="table-cell text-right">
              <span class="salary-amount">{{ formatCurrency(emp.salary?.gross || 0) }}</span>
            </td>
            <td class="table-cell text-center">
              <span class="salary-amount net-amount">{{ formatCurrency(emp.salary?.gross || 0) }}</span>
            </td>
            <td class="table-cell text-center">
              <span class="status-badge" [class.paid]="emp.salary?.isPaid" [class.pending]="!emp.salary?.isPaid">
                {{ emp.salary?.isPaid ? '✅ Paid' : '⏳ Pending' }}
              </span>
            </td>
          </tr>
        }
      </tbody>
      </table>
    </div>

      <!-- Pagination Controls -->
    <div class="pagination">
        <div class="pagination-info">
          <label>Rows per page:</label>
          <select 
            [ngModel]="pageSize()" 
            (ngModelChange)="setPageSize($event)"
            class="page-size-select">
            <option [value]="5">5</option>
            <option [value]="10">10</option>
            <option [value]="20">20</option>
          </select>
        </div>
      
        <div class="pagination-controls">
          <button (click)="setPage(0)" [disabled]="currentPage() === 0" class="page-btn">
            ⏮ First
          </button>
          <button (click)="setPage(currentPage() - 1)" [disabled]="currentPage() === 0" class="page-btn">
            ← Prev
          </button>
          <button (click)="setPage(0)" [class.active]="currentPage() === 0" class="page-number">1</button>
          @if (totalPages() > 1) {
            <button (click)="setPage(1)" [class.active]="currentPage() === 1" class="page-number">2</button>
          }
          @if (totalPages() > 2) {
            <button (click)="setPage(2)" [class.active]="currentPage() === 2" class="page-number">3</button>
          }
          <button (click)="setPage(currentPage() + 1)" [disabled]="currentPage() >= totalPages() - 1" class="page-btn">
            Next →
          </button>
          <button (click)="setPage(totalPages() - 1)" [disabled]="currentPage() >= totalPages() - 1" class="page-btn">
            Last ⏭
          </button>
        </div>
      
        <div class="pagination-summary">
          Page {{ currentPage() + 1 }} of {{ totalPages() }} ({{ employeesWithSalaries().length }} total)
        </div>
    </div>
  </div>

  <!-- Top-up Modal (Enhanced - matching React TopUpModal) -->
  @if (isTopUpModalOpen()) {
    <div class="modal-overlay" (click)="closeTopUpModal()">
      <div class="modal-content insufficient-funds-modal" (click)="$event.stopPropagation()">
        <div class="modal-header insufficient-funds-header">
          <h3 class="modal-title">⚠️ Insufficient Funds</h3>
          <button (click)="closeTopUpModal()" class="close-btn" [disabled]="loading()">✕</button>
        </div>
        <div class="modal-body">
          <div class="insufficient-funds-info">
            <div class="balance-info">
              <p><strong>Current Balance:</strong> <span class="current-balance">{{ formatCurrency(companyBalance()) }}</span></p>
              <p><strong>Total Payroll:</strong> <span class="required-amount">{{ formatCurrency(batchData()?.totalAmount?.amount || 0) }}</span></p>
              <p><strong>Already Paid:</strong> <span class="paid-amount">{{ formatCurrency(batchData()?.executedAmount?.amount || 0) }}</span></p>
              <p><strong>Minimum Top-up:</strong> <span class="minimum-topup">{{ formatCurrency(paymentStatus().requiredTopUp) }}</span></p>
            </div>
            
            <div class="warning-message">
              <p>💰 The company account doesn't have sufficient funds to complete this payroll transfer.</p>
              <p>Please add funds to continue with the payment process.</p>
            </div>
          </div>

          <div class="form-group">
            <label class="form-label">Top-up Amount (BDT) *</label>
            <input 
              type="number" 
              class="form-input topup-amount-input"
              [ngModel]="topUpAmount()"
              (ngModelChange)="topUpAmount.set(+$event)"
              [min]="paymentStatus().requiredTopUp || 1000"
              max="10000000"
              step="1000"
              placeholder="Enter amount"
              [disabled]="loading()"
            />
            <small class="form-hint">Minimum required: {{ formatCurrency(paymentStatus().requiredTopUp || 1000) }}</small>
          </div>
        </div>
        <div class="modal-actions">
          <button (click)="closeTopUpModal()" class="btn btn-secondary" [disabled]="loading()">Cancel Payment</button>
          <button (click)="handleTopUp()" class="btn btn-primary topup-btn" [disabled]="loading() || topUpAmount() <= 0">
            {{ loading() ? '⏳ Processing...' : '💰 Add ' + formatCurrency(topUpAmount()) + ' & Continue' }}
          </button>
        </div>
      </div>
    </div>
  }
</div>

<app-toast-message [message]="message()" (close)="clearMessage()" />
<app-loading-spinner [loading]="loading()" message="Processing..." />
